.global sixteenbitLoad


sixteenbitLoad:
	PUSH {R9-R12, R14}
	LDRB R9, [R7,R4]		;@ HIGHER ORDER BYTE, LOADS NEXT VALUE AT ZPC
	LSL R9, #8				;@ SHIFT HIGHER BYTE BY EIGHT, SO IT BECOMES MSB'S OF 16BIT NUMBER
	ADD R4,  #1			    ;@ INCREMENT R4 BY 1, GRAB NEXT BYTE
	LDRB R10, [R7,R4]		;@ LOWER ORDER BYTE IS NEXT ONE, STORE INTO R10
	ADD R4, R4, #1          ;@ INCREMENT R4
	ADD R7, R9, R10			;@ ADD BOTH TOGETHER, STORE INTO R7
	POP {R9-R12, R15}		
	
